class SubmitOrderData {
  final String mbaOrderNumber;

  final String type;

  final String orderDate;

  final String statusDate;

  final String status;

  final String creditReview;

  final String shopcustomer;

  final List<ItemData> itemList;

  SubmitOrderData({
    required this.mbaOrderNumber,
    required this.type,
    required this.orderDate,
    required this.statusDate,
    required this.status,
    required this.creditReview,
    required this.shopcustomer,
    required this.itemList,
  });

  // ignore: non_constant_identifier_names
  static List<SubmitOrderData> SubmitOrderList = [
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
    SubmitOrderData(
      mbaOrderNumber: 'MBA001',
      type: 'Type 1',
      orderDate: '2023-05-20',
      statusDate: '2023-05-20',
      status: 'pending',
      creditReview: 'inprogress',
      shopcustomer: 'shop',
      itemList: [
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
        ItemData(
          itemNo: '1',
          description: 'Item 1',
          orderQuantity: '10',
          recQuantity: '8',
          shipQty: '8',
          shipDate: '2023-05-21',
          boQty: '0',
          boExtDate: '2023-05-21',
          cancelQty: '3',
          reqQty: '5',
          shipping: 'Shipping 1',
          promo: "Promo 1",
          mbaOrderNumber: 'MBA001',
          errorMessage: 'NA',
        ),
      ],
    ),
  ];
}

class ItemData {
  final String itemNo;
  final String description;
  final String orderQuantity;
  final String recQuantity;
  final String shipQty;
  final String shipDate;
  final String boQty;
  final String boExtDate;
  final String cancelQty;
  final String reqQty;
  final String shipping;
  final String promo;
  final String mbaOrderNumber;
  final String errorMessage;

  ItemData({
    required this.itemNo,
    required this.description,
    required this.orderQuantity,
    required this.recQuantity,
    required this.shipQty,
    required this.shipDate,
    required this.boQty,
    required this.boExtDate,
    required this.cancelQty,
    required this.reqQty,
    required this.shipping,
    required this.promo,
    required this.mbaOrderNumber,
    required this.errorMessage,
  });
}
